In [2]:

import numpy as np


In [3]:
# A class has 4 students and 3 subjects. Their marks are given below. The examiner announces a subject-wise bonus of 5, 2 and 8 marks respectively. Add the bonus to every student in one line using broadcasting, then cap any mark above 100 back to 100 and report how many marks had to be capped.

marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])

bonus=[5,2,8]
print(marks+bonus)

[[ 93  98 103]
 [ 77 101  99]
 [103  87 105]
 [ 65  77  88]]


In [4]:
# Create a 5x5 matrix with a border of 1s and 0s inside, without writing the matrix out by hand.

arr=np.full((5,5),0)
arr[:,0]=1
arr[0,:]=1
arr[-1:]=1
arr[:,-1]=1
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [5]:
# Without running the code, predict the shape of np.arange(30).reshape(5, -1).T. Write your prediction as a comment, then verify it. Also explain in a comment why np.arange(30).reshape(4, -1) fails.

arr=np.arange(30).reshape(5, -1).T
print(arr)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [6]:
# Two arrays of size 4 are given. First join them with hstack and print the shape. Then, using the same two arrays, build a proper (4, 2) two-column table. In a comment, state why the first attempt did not produce two columns.

heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])

har=np.hstack((heights,weights))
print(har)
m=np.array([heights,weights])
print(m.T)

[172 158 181 166  68  52  84  59]
[[172  68]
 [158  52]
 [181  84]
 [166  59]]


In [7]:
# Given a 1D array of 12 monthly sales figures, reshape it into 4 quarters of 3 months each and find which quarter (index) had the highest average sales, along with that average.

sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])


sales=sales.reshape(4,3)
a1=sales[0].mean()
a2=sales[1].mean()
a3=sales[2].mean()
print(a1)
print(sales)

117.66666666666667
[[120 135  98]
 [160 175 190]
 [ 88  92 105]
 [210 198 230]]


In [8]:
# Build a 3x3 multiplication table from the array below using broadcasting only. Do not use loops and do not use np.outer — reshape one of the operands so that broadcasting produces the grid.

a = np.array([2, 3, 4])

r=a.reshape(3,1)*a
print(r)

[[ 4  6  8]
 [ 6  9 12]
 [ 8 12 16]]


In [9]:
a=np.arange(1,21)
a[2::3]=-1
print(a)

[ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1 16 17 -1 19 20]


In [10]:
# For the matrix below, scale every column into the 0 to 1 range using column-wise min-max normalization (x - col_min) / (col_max - col_min). Use broadcasting only — no loops. Verify that each column of the result has a minimum of 0 and a maximum of 1.

X = np.array([[ 50, 1200,  3],
              [ 80, 1500,  9],
              [ 65,  900,  5],
              [ 95, 2000,  7]])

cmin=X.min(axis=0)
cmax=X.max(axis=0)
print((X-cmin)/(cmax-cmin))


[[0.         0.27272727 0.        ]
 [0.66666667 0.54545455 1.        ]
 [0.33333333 0.         0.33333333]
 [1.         1.         0.66666667]]


In [11]:
# Award medals to the scores below using nested np.where: 'Gold' for 90 and above, 'Silver' for 75 and above, 'Bronze' for 60 and above, and 'None' otherwise. Then count how many students received each medal.

scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])
gold=scores[np.where(scores>90)]
silver=scores[np.where((scores>75) & (scores<90))]
bronze=scores[np.where((scores>60) & (scores<75))]
print(len(gold))
print(len(silver))
print(len(bronze))

1
2
2


In [12]:
# Given the matrix below, use np.where with a single condition to obtain the row and column indices of every element greater than 50, print those elements, and then replace them with 0 in a copy of the matrix while leaving the original untouched.

m = np.array([[10, 80, 45],
              [55, 20, 99],
              [70, 33, 12]])



In [14]:
# Three sensors each recorded 5 readings. Stack them so that each sensor becomes a row, and separately stack them so that each sensor becomes a column. Print both shapes and confirm that one is the transpose of the other.

s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])

rs=np.vstack((s1,s2,s3))
print(rs)
print(rs.T)

[[12 15 11 19 14]
 [22 18 25 21 20]
 [31 35 29 33 30]]
[[12 22 31]
 [15 18 35]
 [11 25 29]
 [19 21 33]
 [14 20 30]]


In [15]:
# Create a random 6x6 matrix with seed = 1 and values between 1 and 100, then find the row-wise maximum and the column-wise minimum.

arr=np.random.seed(1)
arr=np.random.randint(1, 101, size=(6, 6))
rm=np.max(arr,axis=1)
cm=np.min(arr,axis=0)
print(rm,cm)

[76 80 85 69 97 64] [ 7  8 17  2 19  6]


In [16]:
# A and B are both 2x3 matrices. Compute A @ B.T and A.T @ B. Print the shape of each result and explain in a comment why both multiplications are legal while A @ B is not.

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9],
              [1, 0, 2]])


print(A @ B.T,(A @ B.T).shape)
print(A.T @ B,(A.T @ B).shape)

[[ 50   7]
 [122  16]] (2, 2)
[[11  8 17]
 [19 16 28]
 [27 24 39]] (3, 3)


In [18]:
# Build a complete multi-step pipeline. Starting from the two arrays below: convert them into column vectors, join them into a single two-column table, attach a third column holding each row's total, then multiply the three-column table by w = [0.5, 0.2, 0.3] to obtain one score per row. Finally use np.where to mark each score as 1 if it is above the average score and 0 otherwise. Report the shape of every intermediate array.

import numpy as np

hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])

# 1. Convert to column vectors
hours_col = hours.reshape(-1, 1)
attendance_col = attendance.reshape(-1, 1)

print("hours_col:")
print(hours_col)
print("Shape:", hours_col.shape)

print("attendance_col:")
print(attendance_col)
print("Shape:", attendance_col.shape)


# 2. Join into a two-column table
cv = np.hstack((hours_col, attendance_col))

print("\nTwo-column table:")
print(cv)
print("Shape:", cv.shape)


# 3. Calculate total for each row
totals = cv.sum(axis=1).reshape(-1, 1)

print("\nTotals:")
print(totals)
print("Shape:", totals.shape)


# 4. Attach totals as third column
table = np.hstack((cv, totals))

print("\nThree-column table:")
print(table)
print("Shape:", table.shape)


# 5. Multiply by weights
w = np.array([0.5, 0.2, 0.3])

scores = table @ w

print("\nScores:")
print(scores)
print("Shape:", scores.shape)


# 6. Calculate average score
average = scores.mean()

print("\nAverage score:", average)
print("Shape:", np.array(average).shape)


# 7. Mark scores above average as 1, otherwise 0
result = np.where(scores > average, 1, 0)

print("\nFinal result:")
print(result)
print("Shape:", result.shape)

hours_col:
[[ 2]
 [ 8]
 [ 5]
 [10]
 [ 3]
 [ 7]]
Shape: (6, 1)
attendance_col:
[[55]
 [92]
 [70]
 [98]
 [60]
 [85]]
Shape: (6, 1)

Two-column table:
[[ 2 55]
 [ 8 92]
 [ 5 70]
 [10 98]
 [ 3 60]
 [ 7 85]]
Shape: (6, 2)

Totals:
[[ 57]
 [100]
 [ 75]
 [108]
 [ 63]
 [ 92]]
Shape: (6, 1)

Three-column table:
[[  2  55  57]
 [  8  92 100]
 [  5  70  75]
 [ 10  98 108]
 [  3  60  63]
 [  7  85  92]]
Shape: (6, 3)

Scores:
[29.1 52.4 39.  57.  32.4 48.1]
Shape: (6,)

Average score: 43.0
Shape: ()

Final result:
[0 1 0 1 0 1]
Shape: (6,)
