In [1]:

import numpy as np


In [2]:
# A class has 4 students and 3 subjects. Their marks are given below. The examiner announces a subject-wise bonus of 5, 2 and 8 marks respectively. Add the bonus to every student in one line using broadcasting, then cap any mark above 100 back to 100 and report how many marks had to be capped.

marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])

bonus=[5,2,8]
print(marks+bonus)

[[ 93  98 103]
 [ 77 101  99]
 [103  87 105]
 [ 65  77  88]]


In [7]:
# Create a 5x5 matrix with a border of 1s and 0s inside, without writing the matrix out by hand.

arr=np.full((5,5),0)
arr[:,0]=1
arr[0,:]=1
arr[-1:]=1
arr[:,-1]=1
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [8]:
# Without running the code, predict the shape of np.arange(30).reshape(5, -1).T. Write your prediction as a comment, then verify it. Also explain in a comment why np.arange(30).reshape(4, -1) fails.

arr=np.arange(30).reshape(5, -1).T
print(arr)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [22]:
# Two arrays of size 4 are given. First join them with hstack and print the shape. Then, using the same two arrays, build a proper (4, 2) two-column table. In a comment, state why the first attempt did not produce two columns.

heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])

har=np.hstack((heights,weights))
print(har)
m=np.array([heights,weights])
print(m.T)

[172 158 181 166  68  52  84  59]
[[172  68]
 [158  52]
 [181  84]
 [166  59]]


In [26]:
# Given a 1D array of 12 monthly sales figures, reshape it into 4 quarters of 3 months each and find which quarter (index) had the highest average sales, along with that average.

sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])


sales=sales.reshape(4,3)
a1=sales[0].mean()
a2=sales[1].mean()
a3=sales[2].mean()
print(a1)
print(sales)

117.66666666666667
[[120 135  98]
 [160 175 190]
 [ 88  92 105]
 [210 198 230]]


In [27]:
# Build a 3x3 multiplication table from the array below using broadcasting only. Do not use loops and do not use np.outer — reshape one of the operands so that broadcasting produces the grid.

a = np.array([2, 3, 4])

r=a.reshape(3,1)*a
print(r)

[[ 4  6  8]
 [ 6  9 12]
 [ 8 12 16]]


In [29]:
a=np.arange(1,21)
a[2::3]=-1
print(a)

[ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1 16 17 -1 19 20]


In [31]:
# For the matrix below, scale every column into the 0 to 1 range using column-wise min-max normalization (x - col_min) / (col_max - col_min). Use broadcasting only — no loops. Verify that each column of the result has a minimum of 0 and a maximum of 1.

X = np.array([[ 50, 1200,  3],
              [ 80, 1500,  9],
              [ 65,  900,  5],
              [ 95, 2000,  7]])

cmin=X.min(axis=0)
cmax=X.max(axis=0)
print((X-cmin)/(cmax-cmin))


[[0.         0.27272727 0.        ]
 [0.66666667 0.54545455 1.        ]
 [0.33333333 0.         0.33333333]
 [1.         1.         0.66666667]]


In [37]:
# Award medals to the scores below using nested np.where: 'Gold' for 90 and above, 'Silver' for 75 and above, 'Bronze' for 60 and above, and 'None' otherwise. Then count how many students received each medal.

scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])
gold=scores[np.where(scores>90)]
silver=scores[np.where((scores>75) & (scores<90))]
bronze=scores[np.where((scores>60) & (scores<75))]
print(len(gold))
print(len(silver))
print(len(bronze))

1
2
2
