In [1]:
import numpy as np

In [ ]:
# Q1. Building the class register
# Three students' marks arrived as three separate lists, and one old record arrived as text.

# Tasks

# Build one table from s1, s2 and s3.
# From that table, print the number of students and the number of subjects as two separate numbers.
# Print the total count of marks entries stored in the table.
# Store the same table as decimals instead of whole numbers.
# Convert old into a form where arithmetic works, then print the total marks of both students.
# Attach old below the main table so that all five students sit in one table.
# Expected output — task 5

# [268 246]
# Expected output — task 6

# [[ 72  85  60  91]
#  [ 45  30  98  55]
#  [ 88  66  74 100]
#  [ 62  71  55  80]
#  [ 49  58  66  73]]

s1 = [72, 85, 60, 91]
s2 = [45, 30, 98, 55]
s3 = [88, 66, 74, 100]
old = np.array([['62', '71', '55', '80'],
                ['49', '58', '66', '73']])
