In [1]:
! pip3 install numpy


In [2]:
import numpy as np
x = np.arange(1,24,2)
print(x)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [3]:
a=np.linspace(5,45,9)
print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


In [5]:
a1=np.arange(1,10)
a2=np.linspace(1,9,9)
print(a1,a1.dtype ,a2,a2.dtype)

[1 2 3 4 5 6 7 8 9] int64 [1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [7]:
i=np.eye(6,dtype='int32')
print(i)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [9]:
j=np.full((3,4),5)
print(j.shape)
print(j.size)
print(j.ndim)

(3, 4)
12
2


In [10]:
a = np.array([2, 4, 6])
b = np.array([2.0, 4.0, 6.0])

print(a.dtype)
print(b.dtype)

b=b.astype(int)

print(a.dtype)
print(b.dtype)

int64
float64
int64
int64


In [11]:
print(np.array([10.9, 25.5, 39.99]).astype(int))

[10 25 39]


In [14]:
arr = np.arange(10, 101, 10)
print(arr[3])
print(arr[-1])
print(arr[-2])

40
100
90


In [18]:

arr = np.arange(10, 101, 10)
slice_arr = arr[2:6]

reverse_arr = arr[::-1]

print(slice_arr)
print(reverse_arr)

[30 40 50 60]
[100  90  80  70  60  50  40  30  20  10]


In [19]:
arr=np.arange(1,21)
r=arr[1::3]
print(r)

[ 2  5  8 11 14 17 20]


In [22]:
arr=np.arange(1,21)
s=arr[2:-2]
print(s)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [27]:
m = np.array([[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]])

print(m[2])
print(m[:,-1])
print(m[1:4,1:4])

[11 12 13 14 15]
[ 5 10 15 20 25]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [29]:
print(m[::4,::4])

[[ 1  5]
 [21 25]]


In [31]:
print(m[::2,::2])

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


In [32]:

marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])
greater60 = marks[marks > 60]
between50_80 = marks[(marks >= 50) & (marks <= 80)]

print(greater60)
print(between50_80)

[91 77 62 85 70]
[56 77 62 70]
