In [1]:
import numpy as np


In [4]:
#  Create an array of the first 12 odd numbers using a single np.arange call.

arr=np.arange(1,25,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [7]:
#  Using np.linspace, create 9 equally spaced values from 5 to 45. Before running, predict the gap between consecutive values - then verify.

arr=np.linspace(5,45,9)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


In [ ]:
# Create np.arange(1, 10) and np.linspace(1, 9, 9). Print both and compare their dtype. Why are they different?

arr = np.arange(1,10)
a=np.linspace(1,9,9)
print(arr,a)
# diff in dtype one gives int and other gives float

[1 2 3 4 5 6 7 8 9] [1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [10]:
# Create a 6x6 identity matrix with integer dtype - the output must show no decimal points

arr=np.eye(6,6,dtype=int)
print(arr)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [14]:
#  Create a 3x4 matrix where every element is 5, and report its shape, size, and ndim.

arr=np.full((3,4),5)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
(3, 4)
12
2


In [16]:
#  Given a = np.array([2, 4, 6]) and b = np.array([2.0, 4.0, 6.0]) - check both dtypes, then convert b to int with astype and verify the dtypes now match.



a = np.array([2, 4, 6])
b = np.array([2.0, 4.0, 6.0])

print(a.dtype,b.dtype)
b=b.astype(int)
print(a.dtype,b.dtype)

int64 float64
int64 int64


In [17]:
# Predict the exact output of np.array([10.9, 25.5, 39.99]).astype(int) before running it. What rule does the result prove?


arr=np.array([10.9,25.5,39.99]).astype(int)

print(arr)

[10 25 39]


In [19]:
#  Given arr = np.arange(10, 101, 10) - extract: (a) the 4th element, (b) the last element using negative indexing, (c) the 2nd-last element.

arr = np.arange(10, 101, 10)
print(arr[3])
print(arr[-1])
print(arr[-2])

40
100
90


In [21]:
# From the same arr, slice out exactly [30 40 50 60], and separately produce the full array in reverse.

a=arr[2:6]
print(a)

[30 40 50 60]


In [22]:
# Given arr = np.arange(1, 21) - extract every 3rd element starting from index 1 (result: 2, 5, 8, ...).

arr = np.arange(1, 21)
a=arr[1::3]
print(a)


[ 2  5  8 11 14 17 20]


In [23]:
# Using one slice only, extract everything from arr (1-20) EXCEPT the first two and the last two elements.

a=arr[2:-2]
print(a)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [29]:
# Using the matrix below, extract: (a) the 3rd row, (b) the last column, (c) the centre 3x3 block.

# m = np.array([[ 1,  2,  3,  4,  5],
#               [ 6,  7,  8,  9, 10],
#               [11, 12, 13, 14, 15],
#               [16, 17, 18, 19, 20],
#               [21, 22, 23, 24, 25]])


m = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])
print(m[3])
print(m[:,4])
print(m[1:4,1:4])

[16 17 18 19 20]
[ 5 10 15 20 25]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [34]:
# From the same matrix, extract the four corner elements as a 2x2 array - using step slicing only.

print(m[0:2,0:2])
print(m[0:2,3:5])
print(m[3:5,0:2])
print(m[3:5,3:5])

[[1 2]
 [6 7]]
[[ 4  5]
 [ 9 10]]
[[16 17]
 [21 22]]
[[19 20]
 [24 25]]


In [35]:
#  From the same matrix, extract every alternate row AND every alternate column at the same time (the result is 3x3).

print(m[::2,::2])

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


In [41]:
# Given the marks array below - (a) extract all marks greater than 60; (b) extract marks between 50 and 80 using two conditions with & (remember the parentheses!).

marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])

print(marks[np.where(marks>60)])
final = marks[np.where((marks>=50)& (marks<=80))]
print(final)



[91 77 62 85 70]
[56 77 62 70]
