In [2]:
import numpy as np


In [6]:
x=np.array([1,2.4,"hello"])
print(x)

['1' '2.4' 'hello']


In [3]:
a1=np.arange(10)
print(a1)
a1=a1+5 ## add 5 to every element
print(a1)
a1=a1*5 ## multiply every element
print(a1)

x=np.arange(10)
y=np.arange(11,21)

print(x)
print(y)
print(x+y)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[25 30 35 40 45 50 55 60 65 70]
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20]
[11 13 15 17 19 21 23 25 27 29]


In [11]:
x=np.arange(6).reshape(2,3)
y=np.arange(3)
print(x)
print(y)
print(x+y)

[[0 1 2]
 [3 4 5]]
[0 1 2]
[[0 2 4]
 [3 5 7]]


In [13]:
x=np.arange(6).reshape(3,2)
y=np.arange(6).reshape(2,3)
print(x)
print(y)
print(x+y)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [16]:
x=np.arange(5)
y=np.arange(1,6)
print(x)
print(y)
print(x==y)
print(x>y)
print(x<y)

[0 1 2 3 4]
[1 2 3 4 5]
[False False False False False]
[False False False False False]
[ True  True  True  True  True]
