In [1]:
import numpy as np



In [5]:
x1=np.array([3,4])
x2=np.array([4])
print(x1+x2)


[7 8]


In [3]:
a=np.array([
    [4,5,6],
    [1,2,3],
    [4,5,6]
])
b=np.array([1,2,3])
print(a+b)

[[5 7 9]
 [2 4 6]
 [5 7 9]]


In [37]:
a=np.array([3,4,2])
b=np.array([3,4])
# print(a+b)
a=np.array([4,4,2])
b=np.array([4,2])
# print(a+b)

In [14]:
a1=np.arange(24).reshape(3,4,2)
print(a1)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [23]:
print(np.array([1,2])+np.array([4,5]))
# print(np.array([4,4,2])+np.array([4,2]))

[5 7]


In [32]:
a=np.arange(12).reshape(4,-1)
print(a)

print(a.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [36]:
a=np.arange(10)
# a1=a.reshape(1,10)
a2=a.reshape(-1,1)
print(a2)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [39]:
a=np.arange(30).reshape(2,5,-1)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [ ]:
a=np.arange(12).reshape(4,3)
print(a)
a1=a.ravel() ##shallow copy

a2=a.flatten() ## deep copy
a2[0]=100
print(a1)
print(a2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[100   1   2   3   4   5   6   7   8   9  10  11]


In [49]:
a1=np.ones(12).reshape(3,4)
a2=np.array([10,20,30]).reshape(-1,1)
print(a1+a2)

[[11. 11. 11. 11.]
 [21. 21. 21. 21.]
 [31. 31. 31. 31.]]


In [51]:
cv=np.arange(1,11).reshape(1,-1)
rv=np.arange(1,11).reshape(-1,1)
print(cv*rv)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [55]:
a=np.arange(1,7).reshape(2,3)
r=a.ravel()
r[0]=33
f=a.flatten()
print(f)
print(r)

[33  2  3  4  5  6]
[33  2  3  4  5  6]


In [65]:
## vstack coloms must be equal
## hstack rows must be equal


a1=np.array([[1,3,4],[2,3,5]])
a2=np.array([[5,6,7],[8,9,10]])
a4=np.concatenate((a1,a2),axis=1)
a3=np.hstack((a1,a2))
a3=np.vstack((a1,a2))
print(a4)
# print(a3)

[[ 1  3  4  5  6  7]
 [ 2  3  5  8  9 10]]


## axis=0 then vstack means runs to coloums
## axis=1 then hstack means runs to rowss

In [ ]:
# axis=0 then vstack means runs to coloums
# axis=1 then hstack means runs to rowss

In [73]:
a=np.array([20,49,55,34])
ans=np.where(a<=40,"false","true")
print(ans)

['false' 'true' 'true' 'false']
