In [2]:
import numpy as np


In [6]:
x=np.array([1,2.4,"hello"])
print(x)

['1' '2.4' 'hello']


In [3]:
a1=np.arange(10)
print(a1)
a1=a1+5 ## add 5 to every element
print(a1)
a1=a1*5 ## multiply every element
print(a1)

x=np.arange(10)
y=np.arange(11,21)

print(x)
print(y)
print(x+y)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[25 30 35 40 45 50 55 60 65 70]
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20]
[11 13 15 17 19 21 23 25 27 29]


In [11]:
x=np.arange(6).reshape(2,3)
y=np.arange(3)
print(x)
print(y)
print(x+y)

[[0 1 2]
 [3 4 5]]
[0 1 2]
[[0 2 4]
 [3 5 7]]


In [13]:
x=np.arange(6).reshape(3,2)
y=np.arange(6).reshape(2,3)
print(x)
print(y)
print(x+y)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [17]:
x=np.arange(5)
y=np.arange(1,6)
print(x)
print(y)
print(x==y)
print(x>y)
print(x<y)

[0 1 2 3 4]
[1 2 3 4 5]
[False False False False False]
[False False False False False]
[ True  True  True  True  True]


In [32]:
np.random.seed(42)
np.random.rand(5)
np.random.randn(3)

array([ 0.27904129,  1.01051528, -0.58087813])

In [36]:
np.random.seed(42)
np.random.randint(1,7,10)
np.random.randint(35,100,20).mean()

np.float64(69.95)

In [54]:
x=np.random.randint(35,100,20)
print(x)
y=x.mean()
z=x.min()
w=x.std()
print(np.argmax(x))
x=x.max()
print(x,y,z,w)

[35 50 95 98 97 56 60 50 85 91 63 81 96 50 82 73 67 57 44 68]
3
98 69.9 35 19.211715175902437


In [42]:
x=np.random.randint(10,50,size=(3,4))
print(x)

[[26 37 39 38]
 [15 44 46 33]
 [38 40 44 42]]


In [ ]:
x=np.arange(6).reshape(2,3)
print(x)
print("row min", x.min(axis=1))
print("col min", x.min(axis=0))
print('sum of arr' , x.sum())
print('sum of row' , x.sum(axis=1))


[[0 1 2]
 [3 4 5]]
row min [0 3]
col min [0 1 2]
sum of arr 15
sum of row [ 3 12]
