In [1]:
import numpy as np

In [5]:
arr=np.array([35,68,42,91,27,55])
print(np.where(arr>50,'pass','fail'))

['fail' 'pass' 'fail' 'pass' 'fail' 'pass']


In [9]:
marks=np.array([92,61,45,78,33,55])
result=np.where(marks>=75,"A",np.where(marks>50,"B","C"))
print(result)

['A' 'B' 'C' 'A' 'C' 'B']


In [12]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a*b)
print(np.dot(a,b))
print(a@b)

[ 4 10 18]
32
32


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
y=np.array([[3,5],[5,6],[7,8]])
print(a)
print(a.T)
print(a.shape)
print(a.T.shape)
print(a@a.T)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
(2, 3)
(3, 2)
[[14 32]
 [32 77]]


In [ ]:
s1=[72,85,60,91]
s2=[45,30,98,55]
s3=[88,66,74,100]
old=np.array([['62','71','55','80'],
        ['49','58','66','73']])

