In [50]:
! pip3 install numpy

In [51]:
import numpy as np
x=np.array([1,2,3,4,5])
x1=np.array([[1,2],[3,4]])
print(x.dtype)
print(type(x))
print(x1)

int64
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


In [52]:
#    fill all elements with zeros
# print(np.zeros(20))
# print(np.zeros(10,dtype='int32'))
# print(np.zeros((3,4)))
# print(np.ones(8))
# print(np.ones(4,dtype='int32'))
# print(np.ones((2,2)))
# print(np.ones((2,2,2,3,4)))
print(np.full((3,4),14))

[[14 14 14 14]
 [14 14 14 14]
 [14 14 14 14]]


In [53]:
print(np.arange(10,5,-1))
print(np.arange(10))
print(np.arange(1,11).reshape(5,2))
print(np.arange(1,13,2).reshape(2,3))

[10  9  8  7  6]
[0 1 2 3 4 5 6 7 8 9]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  3  5]
 [ 7  9 11]]


In [61]:
print(np.linspace(1,10,5))
print(np.linspace(0,1,5))

[ 1.    3.25  5.5   7.75 10.  ]
[0.   0.25 0.5  0.75 1.  ]


In [69]:
print(np.eye(3))
print(np.eye(3,4))
print(np.eye(3,4,k=1))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [76]:
x=np.arange(20).reshape(4,5)
print(x)
print(x.shape)
print(x.size)
print(len(x))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
20
4


In [94]:
#q1

## 1
x=np.arange(1,11)
print(x)
## 2
x1=np.zeros(9).reshape(3,3)
print(x1)
## 3
x2=np.ones(9).reshape(3,3)
print(x2)
## 4
print(np.linspace(0,1,5))
## 5
arr=np.eye(4)

print(arr.shape,"" ,arr.size,"" ,arr.ndim)

## 6
print(np.arange(1,6,dtype='float'))


[ 1  2  3  4  5  6  7  8  9 10]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0.   0.25 0.5  0.75 1.  ]
(4, 4)  16  2
[1. 2. 3. 4. 5.]


In [95]:
arr=np.arange(20).reshape(4,5)
print(arr[2,2])

12


In [ ]:
print(arr)
print(arr[2:,1:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[11 12 13 14]
 [16 17 18 19]]
